markdown: rdiscount
permalink: /:title/
url: http://yanyd.tk
name: Yanyd
author: Yanyd
qq: 659986134
email: yydcookie@gmail.com
duoshuo: yanyd
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 2409320754
github: yanyd
pygments: true
safe: true
paginate: 20
about: "I am a coder , now ! "
